# Generated by Django 5.2.1 on 2025-05-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_recipe_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], default='nonveg', max_length=6),
        ),
    ]
